# Generated by Django 4.1 on 2022-09-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlist_title_alter_mywatchlist_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='watched',
            new_name='is_watched',
        ),
    ]
